### ISSUE TITLE
Experiment: Changesets

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/monorepo-infra-experiments#5]
## Tasks
- [x] Basic integration
- [x] GH actions workflow
- [x] All docs

## Issues and questions
- [x] Figure out "all at once" vs piecemeal
- [x] What happens with a major semver bump in a package depended elsewhere in the monorepo? (If all at once, not an issue)
- [ ] Consider if we want better (custom) changelogs. See urql and changesets docs for this.
- [ ] CI: package up build in build step and re-use in publish?

**Comment by ryan-roemer** [comment]
Moving other issues to separate tickets:
